### ISSUE TITLE
Can I rework docs using Nuxt UI Pro

### ISSUE THREAD

**Issue by Barbapapazes** [unjs/magic-regexp#367]
### 🆒 Your use case

Hello,

Current docs is built with docus which is currently deprecated. Nitro and H3 will use Nuxt UI Pro in a near future. Can I do the same for the current lib?

**Comment by danielroe** [comment]
Oh, I would love that! ❤️

**Comment by moshetanzer** [comment]
@Barbapapazes and @danielroe - had there been any progress with this. Don't mind doing it. Lmk

**Comment by Barbapapazes** [comment]
> @Barbapapazes and @danielroe - had there been any progress with this. Don't mind doing it. Lmk

Hey @moshetanze, no progress since I was waiting for unjs/undocs but now it's released, we can move to it! 😄 If you want to make the PR, feel free!

**Comment by moshetanzer** [comment]
great will try open one soon!
